## Configuration file for .zshrc Aliases


## Functions ( user input )

install() {
        git clone "https://aur.archlinux.org/$1.git"
}

installgit() {
		git clone "https://github.com/$1.git"
}

pkgcommands() {
		pacman -Ql $1 | sed -n -e 's/.*\/bin\///p' | tail -n +2
}



## Aliases

alias zsh='source ~/.zshrc'
alias syncgrub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias ls='exa --icons=always \
        --long \
        --group-directories-first \
        --header'
alias lss='exa --icons=always \
        --long \
        --group-directories-first \
        --header \
        --total-size'
alias lsa='exa --icons=always \
        --long \
        -a \
        --no-time \
        --header \
        --width 10 \
        --total-size \
        --group-directories-first'
alias lsd='exa --icons=always \
        -T \
        --no-permissions \
        --group-directories-first \
        --hyperlink'


## total-size
## long


alias l='yazi'
alias c='clear'
alias clean='
    bleachbit;
    sudo bleachbit;
    paru -Sc
'
alias yay="paru --failfast --color always"


alias ping="ping -c 4 google.com"
alias net+="
        speedtest++ --download;
"
alias net="
        speedtest-cli --no-upload;
        speedtest-cli --no-upload;
        speedtest-cli --no-upload
"
alias bias-bat="sudo cpupower set --perf-bias 15"
alias bias-perf="sudo cpupower set --perf-bias 0"
alias performance="sudo cpupower frequency-set --governor performance"
alias powersave="sudo cpupower frequency-set --governor powersave"
alias conservative="sudo cpupower frequency-set --governor conservative"
alias ondemand="sudo cpupower frequency-set --governor ondemand"
alias cpuinfo="sudo cpupower frequency-info"

alias cat='bat'
alias catt='bat -pp'
#alias catt='bat --theme=OneHalfLight -pp'
#alias cat='bat --theme=OneHalfLight'

alias xhost='xhost +SI:localuser:root'
alias pk="sudo pkill"
alias '?'="sudo systemctl"
alias refresh-keys='sudo /usr/bin/bash -c "/usr/bin/pacman-key --refresh-keys;echo 'PAKtC'"'
alias wget="aria2c"
alias lsblk="lsblk -o NAME,LABEL,SIZE,TYPE,MODEL,MOUNTPOINT,UUID --paths"
#download ncdu to explorer filesystem size
alias icons="cd /usr/share/icons"
alias ..="cd .."
alias publicip="curl -sS https://ysap.sh/ip"
alias ./="cd /"
alias sync="sudo updatedb && sync"
alias top="sudo glances"

alias mpv="mpv --hwdec=vaapi"
alias df="duf"


alias compress="xz -z -9"       #| -3 -6 -9 |#
##                      (fast,bigger_file) <     > (slow,smallest_file)
alias decompress="sudo unxz"

alias backup="bash $HOME/System/maintenance**/home-backup_tar.sh"



#alias toron='
#       systemctl start iptables.service;
#       systemctl start ip6tables.service;
#       systemctl start tor.servicea
#'
#alias toroff='
#       systemctl stop iptables.service;
#       systemctl stop ip6tables.service;
#       systemctl stop tor.service
#'
alias pdf="zathura"
alias libvirt="cd /var/lib/libvirt/images"
alias i="paru -Si "
alias disks="sudo gnome-disks"
alias ai="gemini"
